# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=250)),
                ('frase', models.CharField(max_length=250)),
                ('imagen_frase', models.ImageField(upload_to='fraseimagen')),
                ('fecha', models.DateField(auto_now=True)),
                ('categoria', models.CharField(choices=[('Actualidad', 'Actualidad'), ('Fitnes', 'Fitnes'), ('Nutricion', 'Nutrición')], max_length=40)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='blog')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('mas_info', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField()),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Ruleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen1', models.ImageField(upload_to='Ruleta')),
                ('imagen2', models.ImageField(upload_to='Ruleta')),
                ('imagen3', models.ImageField(upload_to='Ruleta')),
                ('imagen4', models.ImageField(upload_to='Ruleta')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='imagenes',
            field=models.ManyToManyField(related_name='imagenes', to='blog.Imagenes'),
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.ManyToManyField(related_name='videos', to='blog.Video'),
        ),
    ]
