# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 01:57
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160316_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
