# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160321_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
