# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 23:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160321_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 3, 21, 23, 50, 29, 229855, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
