# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='hola que tal'),
            preserve_default=False,
        ),
    ]
