# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerobicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'PRINCIPAL'), ('X-BOX', 'X-BOX'), ('FULL DAY', 'FULL DAY'), ('E-FITH', 'E-FITH'), ('AERODANCE', 'AERODANCE'), ('BODY-FIT', 'BODY-FIT'), ('BAILE', 'BAILE'), ('LOCALIZADO', 'LOCALIZADO'), ('STEP LOCAL', 'STEP LOCAL')], max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='aerobicos')),
            ],
        ),
        migrations.CreateModel(
            name='BestCyclng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'PRINCIPAL'), ('SPINNING', 'SPINNING'), ('SPINNINGFU', 'SPINNING TRABAJO DE FUERZA'), ('SPINNINGI', 'SPINNING TRABAJO DE INTERVALO'), ('SPINNINGFO', 'SPINNING TRABAJO DE FONDO'), ('BESET CYCLING', 'BEST CYCLING')], max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='best')),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lema', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='clases')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='DeportesDeContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'PRINCIPAL'), ('KARATE', 'KARATE'), ('BOXEO', 'BOXEO'), ('MMA WORKOUT', 'MMA WORKOUT'), ('KING BOXING', 'KING BOXING'), ('MUAY THAI', 'MUAY THAI'), ('CAPOEIRA', 'CAPOEIRA')], max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='deportes')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dias', models.ManyToManyField(related_name='dias', to='clases.Dia')),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(help_text='ejemplo de formato en 24 horas (14:00 - 16:00)', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'PRINCIPAL'), ('BAILE MODERNO', 'BAILE MODERNO'), ('FULL BODY KIDS', 'FULL BODY KIDS'), ('MARINERA', 'MARINERA')], max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='talleres')),
                ('horario', models.ManyToManyField(blank=True, null=True, related_name='thorarios', to='clases.Horario')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
            },
        ),
        migrations.AddField(
            model_name='dia',
            name='horas',
            field=models.ManyToManyField(related_name='dhoras', to='clases.Horas'),
        ),
        migrations.AddField(
            model_name='deportesdecontacto',
            name='horario',
            field=models.ManyToManyField(blank=True, null=True, related_name='dhorarios', to='clases.Horario'),
        ),
        migrations.AddField(
            model_name='bestcyclng',
            name='horario',
            field=models.ManyToManyField(blank=True, null=True, related_name='bhorarios', to='clases.Horario'),
        ),
        migrations.AddField(
            model_name='aerobicos',
            name='horario',
            field=models.ManyToManyField(blank=True, null=True, related_name='ahorarios', to='clases.Horario'),
        ),
    ]
