# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerobicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='aerobicos')),
                ('tipo', models.CharField(choices=[('X-BOX', 'X-BOX'), ('FULL DAY', 'FULL DAY'), ('E-FITH', 'E-FITH'), ('AERODANCE', 'AERODANCE'), ('BODY-FIT', 'BODY-FIT'), ('BAILE', 'BAILE'), ('LOCALIZADO', 'LOCALIZADO'), ('STEP LOCAL', 'STEP LOCAL')], max_length=15)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BestCyclng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='bestcyclng')),
                ('tipo', models.CharField(choices=[('', ''), ('', '')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='clases')),
                ('lema', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DeportesDeContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='deportes')),
                ('tipo', models.CharField(choices=[('KARATE', 'KARATE'), ('BOXEO', 'BOXEO'), ('MMA WORKOUT', 'MMA WORKOUT'), ('KING BOXING', 'KING BOXING'), ('MUAY THAI', 'MUAY THAI'), ('CAPOEIRA', 'CAPOEIRA')], max_length=15)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('horas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dias', models.ManyToManyField(related_name='dias', to='clases.Dia')),
            ],
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='talleres')),
                ('tipo', models.CharField(choices=[('BAILE MODERNO', 'BAILE MODERNO'), ('FULL BODY KIDS', 'FULL BODY KIDS'), ('MARINERA', 'MARINERA')], max_length=20)),
                ('descripcion', models.TextField()),
                ('horario', models.ManyToManyField(related_name='thorarios', to='clases.Horario')),
            ],
        ),
        migrations.AddField(
            model_name='deportesdecontacto',
            name='horario',
            field=models.ManyToManyField(related_name='dhorarios', to='clases.Horario'),
        ),
        migrations.AddField(
            model_name='aerobicos',
            name='horario',
            field=models.ManyToManyField(related_name='ahorarios', to='clases.Horario'),
        ),
    ]
