# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestcyclng',
            name='descripcion',
            field=models.TextField(default='hola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestcyclng',
            name='horario',
            field=models.ManyToManyField(related_name='bhorarios', to='clases.Horario'),
        ),
        migrations.AlterField(
            model_name='bestcyclng',
            name='tipo',
            field=models.CharField(choices=[('SPINNING', 'SPINNING'), ('SPINNINGFU', 'SPINNING TRABAJO DE FUERZA'), ('SPINNINGI', 'SPINNING TRABAJO DE INTERVALO'), ('SPINNINGFO', 'SPINNING TRABAJO DE FONDO'), ('BESET CYCLING', 'BEST CYCLING')], max_length=20),
        ),
    ]
