# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='entrenar')),
                ('lema', models.CharField(max_length=250)),
                ('contenido1', models.TextField()),
                ('contenido2', models.TextField()),
                ('contenido3', models.TextField()),
                ('corporativos', models.TextField()),
                ('empresariales', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrenar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='entrenar')),
                ('lema', models.CharField(max_length=250)),
                ('contenido1', models.TextField()),
                ('contenido2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='entrenar')),
                ('lema', models.CharField(max_length=250)),
                ('contenido1', models.TextField()),
                ('contenido2', models.TextField()),
                ('contenido3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lema', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen', models.ImageField(upload_to='servicios')),
            ],
        ),
    ]
