# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20160316_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenar',
            options={'verbose_name': 'Entrenar', 'verbose_name_plural': 'Entrenar'},
        ),
        migrations.AlterModelOptions(
            name='nutricion',
            options={'verbose_name': 'Nutricion', 'verbose_name_plural': 'Nutricion'},
        ),
    ]
