# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20160322_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='entrenar',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='nutricion',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen',
        ),
    ]
